kernel-manager: Command_call

diff --git a/kernel-manager/kernel-manager b/kernel-manager/kernel-manager
--- a/kernel-manager/kernel-manager
+++ b/kernel-manager/kernel-manager
@@ -590,6 +590,77 @@ Command_UpdateGrub(){
     grub-mkconfig -o "/boot/grub/grub.cfg"
 }
 
+#-- Command call --#
+Command_Call(){
+    # メモ
+    # ・関数内でexitしないこと
+    # ・全ての関数に"$@"を渡すこと
+    case "${Command-:""}" in
+        # General command
+        help | "")
+            Command_General_Help "$@"
+            ;;
+        version)
+            Command_General_Version "$@"
+            ;;
+        # List command
+        list-source)
+            Command_List_Source "$@"
+            ;;
+        list-kernel)
+            Command_List_Kernel "$@"
+            ;;
+        # Build command
+        build-kernel)
+            Command_Build_Kernel "$@"
+            ;;
+        # Backup command
+        backup-source | baks)
+            Command_Backup_Source "$@"
+            ;;
+        backup-config | bakc)
+            Command_Backup_Config "$@"
+            ;;
+        backup-kernel | bakk)
+            Command_Backup_Kernel "$@"
+            ;;
+        # Backup List command
+        backup-list-source | bakls)
+            Command_Backup_List_Source "$@"
+            ;;
+        backup-list-config | baklc)
+            Command_Backup_List_Config "$@"
+            ;;
+        backup-list-kernel | baklk)
+            Command_Backup_List_Kernel "$@"
+            ;;
+        # Backup Remove command
+        backup-remove-source | bakrs)
+            Command_Backup_Remove_Source "$@"
+            ;;
+        backup-remove-kernel | bakrk)
+            Command_Backup_Remove_Kernel "$@"
+            ;;
+        backup-remove-config | bakrc)
+            Command_Backup_Remove_Config "$@"
+            ;;
+        # Menuconfig command
+        menuconfig)
+            Command_MenuConfig "$@"
+            ;;
+        # Update grub command
+        update-grub)
+            Command_UpdateGrub "$@"
+            ;;
+        *)
+            Msg.Err "No such command ( '${Command-""}' )"
+            Msg.Err "Please see help with 'help' command"
+            Msg.Err "If you think this is a bug, please report it to the developer."
+            exit 1
+            ;;
+    esac
+}
+
 #-- Parse options --#
 ParseArg SHORT="h" LONG="help,raw,latest" -- "${@}" || exit 1
 eval set -- "${OPTRET[*]}"
@@ -622,71 +693,8 @@ done
 
 Command="${1:-""}"
 shift 1 || true
+Command_Call "${Command}" "$@" || { 
+    Msg.Err "Failed to execute subcommand '$Command'"
+    exit 1
+}
 
-# メモ
-# ・関数内でexitしないこと
-# ・全ての関数に"$@"を渡すこと
-case "${Command-:""}" in
-    # General command
-    help | "")
-        Command_General_Help "$@"
-        ;;
-    version)
-        Command_General_Version "$@"
-        ;;
-    # List command
-    list-source)
-        Command_List_Source "$@"
-        ;;
-    list-kernel)
-        Command_List_Kernel "$@"
-        ;;
-    # Build command
-    build-kernel)
-        Command_Build_Kernel "$@"
-        ;;
-    # Backup command
-    backup-source | baks)
-        Command_Backup_Source "$@"
-        ;;
-    backup-config | bakc)
-        Command_Backup_Config "$@"
-        ;;
-    backup-kernel | bakk)
-        Command_Backup_Kernel "$@"
-        ;;
-    # Backup List command
-    backup-list-source | bakls)
-        Command_Backup_List_Source "$@"
-        ;;
-    backup-list-config | baklc)
-        Command_Backup_List_Config "$@"
-        ;;
-    backup-list-kernel | baklk)
-        Command_Backup_List_Kernel "$@"
-        ;;
-    # Backup Remove command
-    backup-remove-source | bakrs)
-        Command_Backup_Remove_Source "$@"
-        ;;
-    backup-remove-kernel | bakrk)
-        Command_Backup_Remove_Kernel "$@"
-        ;;
-    backup-remove-config | bakrc)
-        Command_Backup_Remove_Config "$@"
-        ;;
-    # Menuconfig command
-    menuconfig)
-        Command_MenuConfig "$@"
-        ;;
-    # Update grub command
-    update-grub)
-        Command_UpdateGrub "$@"
-        ;;
-    *)
-        Msg.Err "No such command ( '${Command-""}' )"
-        Msg.Err "Please see help with 'help' command"
-        Msg.Err "If you think this is a bug, please report it to the developer."
-        exit 1
-        ;;
-esac
